"""milestone 6/7: calendar events, imessage chats and messages

Revision ID: 5787f9860073
Revises: e76b200b7750
Create Date: 2026-08-13 02:22:33.232781
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5787f9860073'
down_revision: Union[str, None] = 'e76b200b7750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('source_event_id', sa.String(length=400), nullable=False),
    sa.Column('calendar_id', sa.String(length=400), nullable=False),
    sa.Column('ical_uid', sa.String(length=400), nullable=True),
    sa.Column('recurring_event_id', sa.String(length=400), nullable=True),
    sa.Column('is_instance_exception', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=1000), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('local_date', sa.String(length=10), nullable=True),
    sa.Column('timezone_name', sa.String(length=80), nullable=True),
    sa.Column('organizer_identity_id', sa.String(length=32), nullable=True),
    sa.Column('attendees', sa.JSON(), nullable=True),
    sa.Column('my_response', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('html_link', sa.String(length=1000), nullable=True),
    sa.Column('updated_at_remote', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organizer_identity_id'], ['identities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_event_id', name='uq_event_source')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_range', ['starts_at', 'ends_at'], unique=False)
        batch_op.create_index('ix_events_series', ['recurring_event_id'], unique=False)
        batch_op.create_index('ix_events_starts', ['starts_at'], unique=False)

    op.create_table('im_chats',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('source_chat_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('participant_ids', sa.JSON(), nullable=True),
    sa.Column('service', sa.String(length=20), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_chat_id', name='uq_chat_source')
    )
    with op.batch_alter_table('im_chats', schema=None) as batch_op:
        batch_op.create_index('ix_chats_last_message', ['last_message_at'], unique=False)

    op.create_table('im_reactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('source_rowid', sa.Integer(), nullable=False),
    sa.Column('target_guid', sa.String(length=200), nullable=False),
    sa.Column('from_identity_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_identity_id'], ['identities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_rowid', name='uq_im_reaction_rowid')
    )
    with op.batch_alter_table('im_reactions', schema=None) as batch_op:
        batch_op.create_index('ix_reactions_target', ['target_guid'], unique=False)

    op.create_table('im_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('chat_id', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('participant_ids', sa.JSON(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['im_chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('im_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_chat_started', ['chat_id', 'started_at'], unique=False)

    op.create_table('im_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('source_rowid', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=120), nullable=True),
    sa.Column('chat_id', sa.String(length=32), nullable=True),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('from_identity_id', sa.String(length=32), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_source', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_from_me', sa.Boolean(), nullable=False),
    sa.Column('service', sa.String(length=20), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('is_unsent', sa.Boolean(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['im_chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_identity_id'], ['identities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['im_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_rowid', name='uq_im_message_rowid')
    )
    with op.batch_alter_table('im_messages', schema=None) as batch_op:
        batch_op.create_index('ix_im_messages_chat_sent', ['chat_id', 'sent_at'], unique=False)
        batch_op.create_index('ix_im_messages_sent', ['sent_at'], unique=False)
        batch_op.create_index('ix_im_messages_session', ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('im_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_im_messages_session')
        batch_op.drop_index('ix_im_messages_sent')
        batch_op.drop_index('ix_im_messages_chat_sent')

    op.drop_table('im_messages')
    with op.batch_alter_table('im_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_chat_started')

    op.drop_table('im_sessions')
    with op.batch_alter_table('im_reactions', schema=None) as batch_op:
        batch_op.drop_index('ix_reactions_target')

    op.drop_table('im_reactions')
    with op.batch_alter_table('im_chats', schema=None) as batch_op:
        batch_op.drop_index('ix_chats_last_message')

    op.drop_table('im_chats')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_starts')
        batch_op.drop_index('ix_events_series')
        batch_op.drop_index('ix_events_range')

    op.drop_table('calendar_events')
    # ### end Alembic commands ###
