"""milestone 2: facts plane, identities, sync state, oauth credentials

Revision ID: e76b200b7750
Revises: 85a14a7fc6f0
Create Date: 2026-08-12 23:50:15.224097
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e76b200b7750'
down_revision: Union[str, None] = '85a14a7fc6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value_normalized', sa.String(length=320), nullable=False),
    sa.Column('value_raw', sa.String(length=320), nullable=False),
    sa.Column('display_names', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('is_role_account', sa.Boolean(), nullable=False),
    sa.Column('is_bulk_sender', sa.Boolean(), nullable=False),
    sa.Column('is_me', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value_normalized', name='uq_identity_value')
    )
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.create_index('ix_identities_is_me', ['is_me'], unique=False)
        batch_op.create_index('ix_identities_role', ['is_role_account'], unique=False)

    op.create_table('persons',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_me', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('identity_id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('signal', sa.String(length=40), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identity_links', schema=None) as batch_op:
        batch_op.create_index('ix_links_identity', ['identity_id'], unique=False)
        batch_op.create_index('ix_links_person', ['person_id'], unique=False)

    op.create_table('message_threads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('source_thread_id', sa.String(length=120), nullable=False),
    sa.Column('subject_normalized', sa.String(length=500), nullable=False),
    sa.Column('participant_ids', sa.JSON(), nullable=True),
    sa.Column('first_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_outbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_thread_id', name='uq_thread_source')
    )
    with op.batch_alter_table('message_threads', schema=None) as batch_op:
        batch_op.create_index('ix_threads_awaiting_reply', ['last_inbound_at', 'last_outbound_at'], unique=False)
        batch_op.create_index('ix_threads_last_message', ['last_message_at'], unique=False)

    op.create_table('oauth_credentials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.Column('encrypted_token', sa.LargeBinary(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'account_email', name='uq_credential_account')
    )
    op.create_table('sync_state',
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('watermark', sa.JSON(), nullable=True),
    sa.Column('recording_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('messages_ingested', sa.Integer(), nullable=False),
    sa.Column('messages_skipped', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('source_message_id', sa.String(length=120), nullable=False),
    sa.Column('rfc_message_id', sa.String(length=400), nullable=True),
    sa.Column('thread_id', sa.String(length=32), nullable=True),
    sa.Column('in_reply_to', sa.String(length=400), nullable=True),
    sa.Column('references_ids', sa.JSON(), nullable=True),
    sa.Column('from_identity_id', sa.String(length=32), nullable=True),
    sa.Column('to_ids', sa.JSON(), nullable=True),
    sa.Column('cc_ids', sa.JSON(), nullable=True),
    sa.Column('bcc_ids', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('subject_normalized', sa.String(length=1000), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html_sanitized', sa.Text(), nullable=True),
    sa.Column('body_clean', sa.Text(), nullable=False),
    sa.Column('signature_block', sa.Text(), nullable=True),
    sa.Column('snippet', sa.String(length=500), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_from_me', sa.Boolean(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('decode_degraded', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('list_id', sa.String(length=300), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_identity_id'], ['identities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_message_id', name='uq_message_source')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_deleted', ['deleted_at'], unique=False)
        batch_op.create_index('ix_messages_received', ['received_at'], unique=False)
        batch_op.create_index('ix_messages_rfc_id', ['rfc_message_id'], unique=False)
        batch_op.create_index('ix_messages_sender_received', ['from_identity_id', 'received_at'], unique=False)
        batch_op.create_index('ix_messages_thread_received', ['thread_id', 'received_at'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=False),
    sa.Column('source_attachment_id', sa.String(length=400), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('local_path', sa.String(length=1000), nullable=True),
    sa.Column('download_status', sa.String(length=30), nullable=False),
    sa.Column('extract_status', sa.String(length=30), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attachments_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_attachments_message', ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_attachments_message')
        batch_op.drop_index('ix_attachments_hash')

    op.drop_table('attachments')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_thread_received')
        batch_op.drop_index('ix_messages_sender_received')
        batch_op.drop_index('ix_messages_rfc_id')
        batch_op.drop_index('ix_messages_received')
        batch_op.drop_index('ix_messages_deleted')

    op.drop_table('messages')
    op.drop_table('sync_state')
    op.drop_table('oauth_credentials')
    with op.batch_alter_table('message_threads', schema=None) as batch_op:
        batch_op.drop_index('ix_threads_last_message')
        batch_op.drop_index('ix_threads_awaiting_reply')

    op.drop_table('message_threads')
    with op.batch_alter_table('identity_links', schema=None) as batch_op:
        batch_op.drop_index('ix_links_person')
        batch_op.drop_index('ix_links_identity')

    op.drop_table('identity_links')
    op.drop_table('persons')
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.drop_index('ix_identities_role')
        batch_op.drop_index('ix_identities_is_me')

    op.drop_table('identities')
    # ### end Alembic commands ###
